### ISSUE TITLE
missing branch: kitkat3

### ISSUE THREAD

**Issue by nosedive** [LiquidSmooth-Old/android_frameworks_base#15]
as stated in manifest for kitkat, there should be a branch called kitkat3 which is missing here
did you delete it accidentially or is the manifest referring to the wrong source?

see https://github.com/LiquidSmooth/android/blob/kitkat/default.xml in line 264:
project path="frameworks/base" name="android_frameworks_base" remote="ls" revision="kitkat3"

**Comment by deadman96385** [comment]
Gerrit went through and removed the KitKat branches for most of the repos because we so not support it and it had not been in a buildable state for a while
