### ISSUE TITLE
W/CallHandlerServiceProxy(  723): InCallUI Connection failed. Enqueuing delayed retry for 2000 ms. retries(0)

### ISSUE THREAD

**Issue by Y300-0100** [LiquidSmooth-Old/android_frameworks_base#6]
Hi, 
sorry for contacting you in this way. I'm trying to build liquidsmooth ROM for unsoported device ( huawei y300). I have managed to make it all working except microphone in incall and out call. I open a tread on modaco ( http://www.modaco.com/topic/373126-development-liquidsmooth-rom-444-test-build/page-1 ) for help but nobody helped much.
I would be thankful for any advice and help with this issue because I really like this ROM.
Thanks in advance
And sorry for my bad English because it's not my native language.

**Comment by MTB3000GT** [comment]
Hey if your still experiencing problems please let me know and I'll try to
help,,, maybe also be able to make it an official liquid build if I have
testers

**Comment by Y300-0100** [comment]
Thanks for your reply and your interest to help. It would be great to have an official liquid for Y300. One thing that I didnt mentioned that breaks build is in frameworks/av/media/lbstagefright/Android.mk is this double ifeq here: https://github.com/LiquidSmooth/android_frameworks_av/blob/kitkat/media/libstagefright/Android.mk#L123
Its break AwesomePlayer to build so when I replace it with:
https://github.com/Y300-0100/android_frameworks_av/blob/kitkat/media/libstagefright/Android.mk#L119 
and the build comes true the end. Also I didn not have time to make proper patch for vold since Dazzozo's patch for /system/vold for swichable pair also break the build (to many warrnings) so I put vold in proprietary for now.
For now only bug with Y300 is microphone only in calls and everythin else working great ( very liquidsmooth and fast :-) ).
Now I made some changes in AudioHardware.cpp localy in device tree and doing build to see did I made some progres.
Once again thank you for your reply and offer for help.
Will keep you informed how the next build come true. 
btw best looking rom I have ever tried.

**Comment by MTB3000GT** [comment]
ok well send me links of your github with the device and ill make it all
work correctly and have you test a build,,once we get a build working ill
send a screen shot to the devs and have it merged to official build

**Comment by Y300-0100** [comment]
https://github.com/Y300-0100
Thanks a LOT.

**Comment by MTB3000GT** [comment]
this device here correct Huawei Ascend Y300 (U8833

also you can send me a message on hangouts its easier

**Comment by Y300-0100** [comment]
Yes , that is correct device.
How can I find you via hangouts?

**Comment by MTB3000GT** [comment]
just search my email
