### ISSUE TITLE
bug. line 95-96

### ISSUE THREAD

**Issue by ShevT** [LiquidSmooth-Old/android_frameworks_base#8]
<string name="setting_reset_hint_message">
<! [CDATA [<p>mở <b>cài đặt</b> <br/> Dưới cá nhân chia: <b>Sao lưu &amp; Thiết lập lại</b> <br/> dưới cá nhân hoá chia: <b>đặt lại tuỳ chọn</b></p>]] ></string>

**Comment by johnnyslt** [comment]
Done:  https://github.com/LiquidSmooth/android_frameworks_base/commit/2b65dc7395e90be93dee83256df3c081947d94c7
